version: '3.3'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
